version: "3.3"

services:
    redis:
        image: redis
        container_name: asr_redis
        restart: always

    database: 
        image: postgres
        container_name: asr_postgres
        environment:         
            POSTGRES_DB: asrdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./pg_data/data/:/var/lib/postgresql/data/
        restart: always

    app:
        image: asr:latest
        container_name: asr_app
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - database
            - redis
        ports:
            - 443:443
            - 80:5000
        volumes:
            - ./app/uploads:/app/uploads
            - ./app/results:/app/results
        environment:
            CELERY_BROKER_URL: redis://redis
            CELERY_RESULT_BACKEND: redis://redis
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
            PYTHONUNBUFFERED: 0
        secrets:
            - azure_key
            - auth_key
        command: /usr/bin/supervisord
        # command: ./run.sh


secrets:
    azure_key:
        file: ./azure.key
    auth_key:
        file: ./auth.key
